# Generated by Django 2.0.2 on 2018-02-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'topics'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dont_forget.Topic'),
        ),
    ]
