# Generated by Django 2.0.2 on 2018-02-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0002_auto_20180210_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='note',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='noteentry',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dont_forget.Note'),
        ),
    ]
