# Generated by Django 2.0.2 on 2018-02-12 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0003_auto_20180211_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteentry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noteentry',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
