# Generated by Django 2.0.2 on 2018-02-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0004_auto_20180212_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteentry',
            name='note',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='NoteEntry',
        ),
    ]
