# Generated by Django 2.0.2 on 2018-02-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0005_auto_20180213_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
