# Generated by Django 2.0.2 on 2018-02-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dont_forget', '0008_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
